image: node:14.17.6

pipelines:
#  default:
  branches:
   develop:
#    - parallel:
    - step:
        size: 2x
        name: Build and Test
        caches:
          - node
        script:
          - yarn install
          - yarn run build
        artifacts:
          - build/**
    - step:
        name: Deploy to Staging
        deployment: Staging
        # trigger: manual  # Uncomment to make this a manual deployment.
        script:
          - pipe: atlassian/scp-deploy:0.3.3
            variables:
              USER: $SSH_USER
              SERVER: $SERVER
              REMOTE_PATH: $REMOTE_PATH
              LOCAL_PATH: '*'
              EXTRA_ARGS: ['-o', 'StrictHostKeyChecking=no']
   master:
#    - parallel:
    - step:
        size: 2x
        name: Build and Test
        caches:
          - node
        script:
          - yarn install
          - yarn run build
        artifacts:
          - build/**
    - step:
        name: Deploy to Production
        deployment: Production
        # trigger: manual  # Uncomment to make this a manual deployment.
        script:
          - pipe: atlassian/scp-deploy:0.3.3
            variables:
              USER: $SSH_USER
              SERVER: $SERVER
              REMOTE_PATH: $REMOTE_PATH
              LOCAL_PATH: '*'
              EXTRA_ARGS: ['-o', 'StrictHostKeyChecking=no']