const IQBAL_BUSINESS_ID = 12092,
  APNA_FORM_BUSINESS_ID = 12185,
  DWP_BUSINESS_ID = 12230,
  DWP_STAGING_BUSINESS_ID = 12180,
  AMANAT_STAGING_BUSINESS_ID = 12208,
  AMANAT_BUSINESS_ID = 12257;

export {
  DWP_BUSINESS_ID,
  DWP_STAGING_BUSINESS_ID,
  AMANAT_BUSINESS_ID,
  AMANAT_STAGING_BUSINESS_ID,
  IQBAL_BUSINESS_ID,
};
