import { StyleSheet, Font } from '@react-pdf/renderer'
import Regular from '../fonts/roboto/Roboto-Regular.ttf'
import Italic from '../fonts/roboto/Roboto-Italic.ttf'
import Bold from '../fonts/roboto/Roboto-Bold.ttf'
import Black from '../fonts/roboto/Roboto-Black.ttf'
Font.register({
  family: 'Roboto',
  fonts: [
    { src: Regular },
    { src: Italic, fontStyle: 'italic' },
    { src: Bold, fontWeight: 'bold' },
    { src: Black, fontWeight: 'heavy' },
  ],
})

export const styles = StyleSheet.create({
  page: {
    backgroundColor: 'white',
  },
  spaceBetweenRow: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  categoryCol: {
    width: '9%',
    justifyContent: 'flex-start',
    //  marginLeft: 'auto',
    marginRight: '10px',
    fontSize: 8,
    fontFamily: 'Roboto',
    marginTop: 5,
    marginBottom: 5,
    //zIndex: 1000000,
  },
  Detailrow: {
    overflow: 'hidden',
    width: '100%',
    flexDirection: 'row',
    maxWidth: '100%',
  },
  row: {
    overflow: 'hidden',
    width: '100%',
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  rowSection: {
    width: '100%',
    flexDirection: 'row',
  },
  column: {
    display: 'flex',
    flexDirection: 'column',
    marginTop: '24px',
  },
  packingSlip: {
    paddingTop: 25,
    paddingLeft: 30,
    fontSize: 24,
    marginTop: 10,
    color: '#D9134D',
    fontFamily: 'Roboto',
  },
  pdfEatOutNameView: {
    display: 'flex',
    //  justifyContent: 'center',
    alignSelf: 'center',
  },
  pdfEatOutName: {
    marginRight: 30,
    fontSize: 12,
    marginTop: 10,
    paddingTop: 25,
  },
  image: {
    width: '60px',
    height: '60px',
    marginLeft: 'auto',
    marginRight: 30,
    objectFit: 'contain',
  },
  texth1: {
    marginLeft: 'auto',
    marginRight: 30,
    fontSize: 12,
    marginTop: 10,
    paddingTop: 25,
  },
  divider: {
    marginLeft: 30,
    marginRight: 30,
    marginBottom: 3,
    width: '90%',
    height: 1,
    backgroundColor: '#c4c2c2',
    marginTop: 2,
    // color: 'red',
  },
  headerDivider: {
    marginLeft: 30,
    marginRight: 30,
    marginBottom: 3,
    //marginTop: 1,
    width: '90%',
    backgroundColor: '#c4c2c2',
    height: 1,
  },
  skuB: {
    marginLeft: 30,
    padding: '4px',
    fontSize: 10,
    marginTop: 1,
    marginBottom: 5,
    color: '#757575',
    fontFamily: 'Roboto',
  },
  statusCss: {
    padding: '4px',
    fontSize: 10,
    marginTop: 1,
    marginBottom: 6,
    color: '#000000',

    fontFamily: 'Roboto',
  },
  statusCommentCss: {
    // width: '40%',
    // justifyContent: 'flex-start',
    // padding: '4px',
    fontSize: 10,
    marginTop: 1,
    marginLeft: 10,
    // marginBottom: 6,
    color: '#000000',
    fontFamily: 'Roboto',
  },
  tablecolPdf: {
    lineHeight: 1.1,
    width: '11%',
    justifyContent: 'flex-start',
    marginLeft: 'auto',
    marginRight: 'auto',
    fontSize: 8,
    //fontFamily: "Times",
    marginTop: 5,
    marginBottom: 5,
    //zIndex: 1000000,
    // wordWrap: "break-word"
  },
  sku: {
    fontFamily: 'Roboto',
    // width: '40%',
    justifyContent: 'flex-start',
    marginLeft: '34px',
    fontSize: 10,
    marginTop: 2,
    // marginBottom: 1,
    color: '#757575',
  },
  pcode: {
    lineHeight: 1.1,
    width: '40%',
    marginLeft: 10,
    justifyContent: 'flex-end',
    marginRight: 10,
    fontSize: 8,
    marginTop: 1,
    marginBottom: 1,
    color: '#121111',
  },
  tablerowhead: {
    flexDirection: 'row',
    marginLeft: 30,
    paddingLeft: 2,
    paddingRight: 2,
    //marginTop: 8,
    backgroundColor: '#F5F5F5',
    //borderTop: 1,
    borderBottom: 1,
    borderLeft: 1,
    borderRight: 1,
    borderColor: '#f2f0f1',
    // borderStyle: 'solid',
    borderRadius: 0,
  },
  tablerowheadPdf: {
    flexDirection: 'row',
    marginBottom: 10,
  },
  tableBox: {
    borderBottom: 1,
    borderLeft: 1,
    borderRight: 1,
    borderColor: '#f2f0f1',
    //  borderStyle: 'solid',
    borderRadius: 0,
  },
  headBox: {
    marginLeft: 30,
    padding: 10,
    marginTop: 8,
    paddingTop: 14,
    paddingBottom: 14,
    paddingLeft: 16,
    overflow: 'hidden',
    width: 250,
    backgroundColor: '#F5F5F5',

    borderTop: 1,
    borderBottom: 1,
    borderLeft: 1,
    borderRight: 1,
    borderColor: '#f2f0f1',
    borderStyle: 'solid',
    borderRadius: 0,
  },
  cardSectionCSS: {
    display: 'flex',
    flexDirection: 'column',
  },
  detailBox: {
    marginLeft: 30,
    width: 250,
    height: 130,
    paddingTop: 20,
    paddingBottom: 30,
    paddingLeft: 16,
    borderTop: 1,
    borderBottom: 1,
    borderLeft: 1,
    borderRight: 1,
    borderColor: '#f2f0f1',
    borderStyle: 'solid',
    borderRadius: 0,
    display: 'flex',
    flexDirection: 'column',
  },
  detailBoxCustomerDetail: {
    marginLeft: 30,
    width: 250,
    height: 130,
    paddingTop: '20px',
    paddingBottom: 30,
    paddingLeft: '16px',
    borderTop: 1,
    borderBottom: 1,
    borderLeft: 1,
    borderRight: 1,
    borderColor: '#f2f0f1',
    borderStyle: 'solid',
    borderRadius: 0,
    display: 'flex',
    flexDirection: 'column',
    marginBottom: 10,
  },
  boxTextCss: {
    fontFamily: 'Roboto',
    width: '40%',
    fontSize: 10,
    justifyContent: 'flex-start',
    marginTop: 2,
    color: '#212121',
  },
  detailBoxTextCss: {
    fontFamily: 'Roboto',
    // width: '40%',
    marginTop: 2,
    justifyContent: 'flex-start',
    fontSize: 9,
    color: '#757575',
  },
  detailBoldTextCss: {
    lineHeight: '15px',
    fontFamily: 'Roboto',
    //width: '40%',
    justifyContent: 'flex-start',
    fontSize: 9,
    marginTop: 2,
    color: '#212121',
    marginLeft: '0px',
  },
  numbertablecol: {
    width: '10%',
    justifyContent: 'flex-start',
  },
  tablecol: {
    width: '20%',
    justifyContent: 'flex-start',
    marginLeft: 2,
  },
  tableColPdf: {
    lineHeight: 1.1,
    width: '11%',
    justifyContent: 'flex-start',
    marginLeft: 'auto',
    marginRight: 'auto',
    fontSize: 8,
    fontFamily: 'Roboto',
    marginTop: 5,
    marginBottom: 5,
  },

  tableColPdfBrand: {
    lineHeight: 1.1,
    width: '11%',
    justifyContent: 'flex-start',
    marginLeft: 'auto',
    marginRight: 'auto',
    fontSize: 8,
    fontFamily: 'Roboto',
    marginTop: 5,
    marginBottom: 5,
  },
  tableColPdfPrice: {
    lineHeight: 1.1,
    width: '11%',
    justifyContent: 'flex-start',
    marginLeft: 'auto',
    marginRight: 'auto',
    fontSize: 8,
    fontFamily: 'Roboto',
    marginTop: 5,
    marginBottom: 5,
  },
  tableColPdfItemHead: {
    lineHeight: 1.1,
    width: '6%',
    justifyContent: 'flex-start',
    marginLeft: 'auto',
    marginRight: 'auto',
    fontSize: 8,
    fontFamily: 'Roboto',
    marginTop: 5,
    marginBottom: 5,
  },
  tableColPdfCategoryHead: {
    lineHeight: 1.1,
    width: '9%',
    justifyContent: 'flex-start',
    marginLeft: 'auto',
    marginRight: 'auto',
    fontSize: 8,
    fontFamily: 'Roboto',
    marginTop: 5,
    marginBottom: 5,
  },

  tableColPdfItem: {
    lineHeight: 1.1,
    width: '13%',
    justifyContent: 'flex-start',
    marginLeft: 'auto',
    marginRight: 'auto',
    fontSize: 8,
    fontFamily: 'Roboto',
    marginTop: 5,
    marginBottom: 5,
  },
  itemColPdf: {
    lineHeight: 1.1,
    width: '13%',
    justifyContent: 'flex-start',
    marginLeft: 'auto',
    marginRight: '10px',
    fontSize: 8,
    fontFamily: 'Roboto',
    marginTop: 5,
    marginBottom: 5,
  },
  texttcomPdf: {
    marginLeft: 'auto',
    marginRight: 'auto',
    fontSize: 8,
    fontFamily: 'Roboto',
    color: 'black',
    marginTop: 1,
    marginBottom: 1,
    lineHeight: 1.08,
  },
  textDonePdf: {
    fontSize: 7,
    fontFamily: 'Roboto',
    marginTop: 1,
    marginBottom: 1,
    lineHeight: 1.1,
    color: 'black',
  },
  brandtablecol: {
    width: '10%',
    justifyContent: 'flex-start',
    marginLeft: 2,
  },
  itemtablecol: {
    width: '45%',
    fontSize: 10,
    justifyContent: 'flex-start',
    marginRight: 10,
    //  wordWrap: 'break-word',
  },
  textth2: {
    marginTop: 4,
    marginBottom: 4,
    fontSize: 10,
    // fontWeight: "bold",
  },
  tablePadding: {
    display: 'flex',
    flexDirection: 'row',
    padding: 4,
    marginLeft: 10,
  },
  tablerow: {
    display: 'flex',
    flexDirection: 'row',
    paddingTop: 4,
    marginTop: 5,
    marginLeft: 14,
  },
  // texttPdf: {
  //   marginTop: 4,
  //   marginBottom: 4,
  //   fontSize: 10,
  //   marginLeft: 5,
  // },
  numbertextt: {
    marginLeft: 'auto',
    marginRight: 'auto',
    fontSize: 10,
    lineHeight: 1,
  },
  textt: {
    lineHeight: 1,
    marginLeft: 2,
    fontSize: 10,
  },
  texttPdf: {
    marginLeft: 5,
    marginRight: 'auto',
    fontSize: 10,
    fontFamily: 'Roboto',
    marginTop: 1,
    marginBottom: 1,
    lineHeight: 1.1,
  },
  bolder: {
    lineHeight: 1,
    marginLeft: 2,
    fontSize: 12,
  },
  spacer: {
    marginBottom: 6,
    flexDirection: 'row',
  },
  rowend: {
    width: '100%',
    flexDirection: 'row',
    //textAlign: 'right',
    marginBottom: 3,
  },
  currencyrowTotalQuantity: {
    //width: '50vw',
    // marginTop: 4,
    ///   marginBottom: 4,
    fontSize: 10,
    marginLeft: 40,
  },
  currencyrow2: {
    width: '40%',
  },
  texth2th: {
    marginLeft: 200,
    fontSize: 10,
  },
  texth2tDeliveryCharges: {
    marginLeft: 40,
    fontSize: 10,
  },
  textTax: {
    marginLeft: 220,
    fontSize: 10,
  },
  texServiceCharges: {
    marginLeft: 40,
    fontSize: 10,
  },
  texth2tDiscount: {
    marginLeft: 200,
    fontSize: 10,
  },
  texth2t: {
    marginLeft: 80,
    fontSize: 10,
    //  color: 'red',
  },
  texttcom: {
    marginLeft: '2px',
    fontSize: 8,
    color: 'black',
    lineHeight: 0.8,
  },
  texth2g2: {
    lineHeight: 1.1,
    fontSize: 14,
    fontWeight: 'bold',
    marginTop: 4,
    marginBottom: 6,
    marginLeft: 120,
  },
  texttaddone: {
    lineHeight: 1,
    fontSize: 7,
    color: 'black',
  },
  boldOptionSet: {
    lineHeight: 1,
    fontSize: 10,
  },
  footer: {
    width: '90%',
    flexDirection: 'row',
    marginLeft: 'auto',
    marginRight: 'auto',
    marginTop: 1,
  },
  hst: {
    justifyContent: 'flex-start',
    marginRight: 'auto',
    fontSize: 9,
    color: '#121111',
  },
  phone: {
    justifyContent: 'flex-start',
    marginLeft: 'auto',
    fontSize: 9,
    color: '#121111',
  },
  email: {
    justifyContent: 'flex-start',
    marginLeft: 'auto',
    marginRight: 'auto',
    fontSize: 9,
    color: '#121111',
  },
})
