import { StyleSheet, Font } from '@react-pdf/renderer'
import Regular from '../assets/fonts/roboto/Roboto-Regular.ttf'
import Italic from '../assets/fonts/roboto/Roboto-Italic.ttf'
import Bold from '../assets/fonts/roboto/Roboto-Bold.ttf'
import Black from '../assets/fonts/roboto/Roboto-Black.ttf'
Font.register({
  family: 'Roboto',
  fonts: [
    { src: Regular },
    { src: Italic, fontStyle: 'italic' },
    { src: Bold, fontWeight: 'bold' },
    { src: Black, fontWeight: 'heavy' },
  ],
})

export const styles = StyleSheet.create({
  page: {
    backgroundColor: 'white',
  },
  spaceBetweenRow: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  categoryCol: {
    width: '9%',
    justifyContent: 'flex-start',
    marginRight: '10px',
    fontSize: 8,
    fontFamily: 'Roboto',
    marginTop: 5,
    marginBottom: 5,
  },
  Detailrow: {
    overflow: 'hidden',
    width: '100%',
    flexDirection: 'row',
    maxWidth: '100%',
  },
  row: {
    overflow: 'hidden',
    width: '100%',
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  rowSection: {
    width: '100%',
    flexDirection: 'row',
  },
  column: {
    display: 'flex',
    flexDirection: 'column',
    marginTop: '24px',
  },
  packingSlip: {
    paddingTop: 25,
    paddingLeft: 30,
    fontSize: 24,
    marginTop: 10,
    color: '#D9134D',
    fontFamily: 'Roboto',
  },
  pdfEatOutNameView: {
    display: 'flex',
    alignSelf: 'center',
  },
  pdfEatOutName: {
    marginRight: 30,
    fontSize: 12,
    marginTop: 10,
    paddingTop: 25,
  },
  image: {
    width: '60px',
    height: '60px',
    marginLeft: 'auto',
    marginRight: 30,
    objectFit: 'contain',
  },
  texth1: {
    marginLeft: 'auto',
    marginRight: 30,
    fontSize: 12,
    marginTop: 10,
    paddingTop: 25,
  },
  divider: {
    marginLeft: 30,
    marginRight: 30,
    marginBottom: 3,
    width: '90%',
    height: 1,
    backgroundColor: '#c4c2c2',
    marginTop: 2,
  },
  headerDivider: {
    marginLeft: 30,
    marginRight: 30,
    marginBottom: 3,
    width: '90%',
    backgroundColor: '#c4c2c2',
    height: 1,
  },
  skuB: {
    marginLeft: 30,
    padding: '4px',
    fontSize: 10,
    marginTop: 1,
    marginBottom: 5,
    color: '#757575',
    fontFamily: 'Roboto',
  },
  statusCss: {
    padding: '4px',
    fontSize: 10,
    marginTop: 1,
    marginBottom: 6,
    color: '#000000',

    fontFamily: 'Roboto',
  },
  statusCommentCss: {
    fontSize: 10,
    marginTop: 1,
    marginLeft: 10,
    color: '#000000',
    fontFamily: 'Roboto',
  },
  tablecolPdf: {
    lineHeight: 1.1,
    width: '11%',
    justifyContent: 'flex-start',
    marginLeft: 'auto',
    marginRight: 'auto',
    fontSize: 8,
    marginTop: 5,
    marginBottom: 5,
  },
  sku: {
    fontFamily: 'Roboto',
    justifyContent: 'flex-start',
    marginLeft: '34px',
    fontSize: 10,
    marginTop: 2,
    color: '#757575',
  },
  pcode: {
    lineHeight: 1.1,
    width: '40%',
    marginLeft: 10,
    justifyContent: 'flex-end',
    marginRight: 10,
    fontSize: 8,
    marginTop: 1,
    marginBottom: 1,
    color: '#121111',
  },
  tablerowhead: {
    flexDirection: 'row',
    marginLeft: 30,
    marginRight: 30,
    paddingLeft: 2,
    paddingRight: 2,
    backgroundColor: '#F5F5F5',
    borderBottom: 1,
    borderLeft: 1,
    borderRight: 1,
    borderColor: '#f2f0f1',
    borderRadius: 0,
  },
  tablerowheadPdf: {
    flexDirection: 'row',
    marginBottom: 10,
  },
  tableBox: {
    borderBottom: 1,
    borderLeft: 1,
    borderRight: 1,
    borderColor: '#f2f0f1',

    borderRadius: 0,
  },
  headBox: {
    marginLeft: 30,
    padding: 10,
    marginTop: 8,
    paddingTop: 14,
    paddingBottom: 14,
    paddingLeft: 16,
    overflow: 'hidden',
    width: 250,
    backgroundColor: '#F5F5F5',

    borderTop: 1,
    borderBottom: 1,
    borderLeft: 1,
    borderRight: 1,
    borderColor: '#f2f0f1',
    borderStyle: 'solid',
    borderRadius: 0,
  },
  cardSectionCSS: {
    display: 'flex',
    flexDirection: 'column',
  },
  detailBox: {
    marginLeft: 30,
    width: 250,
    height: 130,
    paddingTop: 20,
    paddingBottom: 30,
    paddingLeft: 16,
    borderTop: 1,
    borderBottom: 1,
    borderLeft: 1,
    borderRight: 1,
    borderColor: '#f2f0f1',
    borderStyle: 'solid',
    borderRadius: 0,
    display: 'flex',
    flexDirection: 'column',
  },
  detailBoxCustomerDetail: {
    marginLeft: 30,
    width: 250,
    height: 130,
    paddingTop: '20px',
    paddingBottom: 30,
    paddingLeft: '16px',
    borderTop: 1,
    borderBottom: 1,
    borderLeft: 1,
    borderRight: 1,
    borderColor: '#f2f0f1',
    borderStyle: 'solid',
    borderRadius: 0,
    display: 'flex',
    flexDirection: 'column',
    marginBottom: 10,
  },
  boxTextCss: {
    fontFamily: 'Roboto',
    width: '40%',
    fontSize: 10,
    justifyContent: 'flex-start',
    marginTop: 2,
    color: '#212121',
  },
  detailBoxTextCss: {
    fontFamily: 'Roboto',
    marginTop: 2,
    justifyContent: 'flex-start',
    fontSize: 9,
    color: '#757575',
  },
  detailBoldTextCss: {
    lineHeight: '15px',
    fontFamily: 'Roboto',
    justifyContent: 'flex-start',
    fontSize: 9,
    marginTop: 2,
    color: '#212121',
    marginLeft: '0px',
  },
  detailBoldTextDate: {
    lineHeight: '15px',
    fontFamily: 'Roboto',
    justifyContent: 'flex-start',
    fontSize: 9,
    marginTop: 2,
    color: '#212121',
    marginLeft: 50,
  },
  detailBoldTextCssOrderId: {
    lineHeight: '15px',
    fontFamily: 'Roboto',
    justifyContent: 'flex-start',
    fontSize: 9,
    marginTop: 2,
    color: '#212121',
    marginLeft: 40,
  },
  detailBoxTextCssPaymentType: {
    lineHeight: '15px',
    fontFamily: 'Roboto',
    justifyContent: 'flex-start',
    fontSize: 9,
    marginTop: 2,
    color: '#212121',
    marginLeft: 10,
  },
  detailBoxTextCssPaymentTypeOderId: {
    lineHeight: '15px',
    fontFamily: 'Roboto',
    justifyContent: 'flex-start',
    fontSize: 9,
    marginTop: 2,
    color: '#212121',
    marginLeft: 22,
  },
  detailBoxTextCssPaymentTypeName: {
    lineHeight: '15px',
    fontFamily: 'Roboto',
    justifyContent: 'flex-start',
    fontSize: 9,
    marginTop: 2,
    color: '#212121',
    marginLeft: 40,
  },
  detailBoxTextCssPaymentTypeMobile: {
    lineHeight: '15px',
    fontFamily: 'Roboto',
    justifyContent: 'flex-start',
    fontSize: 9,
    marginTop: 2,
    color: '#212121',
    marginLeft: 37,
  },
  detailBoxTextCssPaymentTypeAddress: {
    lineHeight: '15px',
    fontFamily: 'Roboto',
    // justifyContent: 'flex-start',
    fontSize: 9,
    marginTop: 2,
    color: '#212121',
    marginLeft: 30,
    flexWrap: 'wrap',
    // width: '100%',
    paddingRight: 10,
  },
  detailBoxTextCssNote: {
    lineHeight: '15px',
    fontFamily: 'Roboto',
    justifyContent: 'flex-start',
    fontSize: 9,
    marginTop: 2,
    color: '#212121',
    marginLeft: 44,
  },
  detailBoldTextCssNote: {
    lineHeight: '15px',
    fontFamily: 'Roboto',
    justifyContent: 'flex-start',
    fontSize: 9,
    marginTop: 2,
    color: '#212121',
    marginLeft: 46,
  },
  detailBoxTextCssPaymentTypeDeliveryTime: {
    lineHeight: '15px',
    fontFamily: 'Roboto',
    justifyContent: 'flex-start',
    fontSize: 9,
    marginTop: 2,
    color: '#212121',
    marginLeft: 10,
  },
  numbertablecol: {
    width: '10%',
    justifyContent: 'flex-start',
  },
  numbertablecolQuantity: {
    width: '10%',
    justifyContent: 'flex-start',
    marginLeft: 5,
  },
  tablecol: {
    width: '19%',
    justifyContent: 'flex-start',
    marginLeft: 2,
  },
  tablecolItem: {
    width: '17%',
    justifyContent: 'flex-start',
    marginLeft: 2,
  },
  tableColPdf: {
    lineHeight: 1.1,
    width: '11%',
    justifyContent: 'flex-start',
    marginLeft: 'auto',
    marginRight: 'auto',
    fontSize: 8,
    fontFamily: 'Roboto',
    marginTop: 5,
    marginBottom: 5,
  },
  tableColPdfWeight: {
    lineHeight: 1.1,
    width: '12%',
    justifyContent: 'flex-start',
    marginLeft: 'auto',
    marginRight: 'auto',
    fontSize: 8,
    fontFamily: 'Roboto',
    marginTop: 5,
    marginBottom: 5,
  },

  tableColPdfBrand: {
    lineHeight: 1.1,
    width: '12%',
    justifyContent: 'flex-start',
    marginLeft: 'auto',

    fontSize: 8,
    fontFamily: 'Roboto',
    marginTop: 5,
    marginBottom: 5,
    marginRight: 5,
  },
  tableColPdfPrice: {
    lineHeight: 1.1,
    width: '13%',
    marginLeft: 10,
    fontSize: 8,
    fontFamily: 'Roboto',
    marginTop: 5,
    marginBottom: 5,
  },
  tablecolPdfAmount: {
    lineHeight: 1.1,
    width: '13%',
    marginLeft: 10,
    fontSize: 8,
    fontFamily: 'Roboto',
    marginTop: 5,
    marginBottom: 5,
  },
  tableColPdfItemHead: {
    lineHeight: 1.1,
    width: '11%',
    justifyContent: 'flex-start',
    marginLeft: 'auto',
    marginRight: 'auto',
    fontSize: 8,
    fontFamily: 'Roboto',
    marginTop: 5,
    marginBottom: 5,
  },
  tableColPdfAmountHead: {
    lineHeight: 1.1,
    width: '11%',
    justifyContent: 'flex-start',
    marginLeft: 'auto',
    marginRight: 'auto',
    fontSize: 8,
    fontFamily: 'Roboto',
    marginTop: 5,
    marginBottom: 5,
  },

  tableColPdfItemRow: {
    lineHeight: 1.1,
    width: '4%',
    marginLeft: 60,
    paddingLeft: 2,
    fontSize: 8,
    fontFamily: 'Roboto',
    marginTop: 5,
    marginBottom: 5,
  },
  tableColPdfCategoryHead: {
    lineHeight: 1.1,
    width: '12%',
    justifyContent: 'flex-start',
    marginLeft: 'auto',
    marginRight: 'auto',
    fontSize: 8,
    fontFamily: 'Roboto',
    marginTop: 5,
    marginBottom: 5,
  },

  tableColPdfItem: {
    lineHeight: 1.1,
    width: '14%',
    justifyContent: 'flex-start',
    marginLeft: 'auto',
    marginRight: 'auto',
    fontSize: 8,
    fontFamily: 'Roboto',
    marginTop: 5,
    marginBottom: 5,
  },
  itemColPdf: {
    lineHeight: 1.1,
    width: '13%',
    justifyContent: 'flex-start',
    marginLeft: 'auto',
    marginRight: '10px',
    fontSize: 8,
    fontFamily: 'Roboto',
    marginTop: 5,
    marginBottom: 5,
  },
  tableColPdfBrandHead: {
    lineHeight: 1.1,
    width: '11%',
    justifyContent: 'flex-start',
    marginLeft: 'auto',
    marginRight: '10px',
    fontSize: 8,
    fontFamily: 'Roboto',
    marginTop: 5,
    marginBottom: 5,
  },
  tableColPdfBrandHeadPdf: {
    lineHeight: 1.1,
    width: '13%',
    justifyContent: 'flex-start',
    marginLeft: 'auto',
    marginRight: '10px',
    fontSize: 8,
    fontFamily: 'Roboto',
    marginTop: 5,
    marginBottom: 5,
  },
  texttcomPdf: {
    marginLeft: 'auto',
    marginRight: 'auto',
    fontSize: 8,
    fontFamily: 'Roboto',
    color: 'black',
    marginTop: 1,
    marginBottom: 1,
    lineHeight: 1.08,
  },
  textDonePdf: {
    fontSize: 7,
    fontFamily: 'Roboto',
    marginTop: 1,
    marginBottom: 1,
    lineHeight: 1.1,
    color: 'black',
  },
  brandtablecol: {
    width: '20%',
    justifyContent: 'flex-start',
    marginLeft: 2,
  },
  itemtablecol: {
    width: '40%',
    fontSize: 10,
    justifyContent: 'flex-start',
    marginRight: 10,
  },
  textth2: {
    marginTop: 4,
    marginBottom: 4,
    fontSize: 10,
  },
  tablePadding: {
    display: 'flex',
    flexDirection: 'row',
    padding: 4,
    marginLeft: 10,
  },
  tablerow: {
    display: 'flex',
    flexDirection: 'row',
    paddingTop: 4,
    marginTop: 5,
    marginLeft: 14,
  },
  tablerowPackingSlip: {
    display: 'flex',
    flexDirection: 'row',
    paddingTop: 4,
    marginTop: 5,
    marginLeft: 46,
  },

  numbertextt: {
    marginLeft: 'auto',
    marginRight: 'auto',
    fontSize: 10,
    lineHeight: 1,
  },
  textt: {
    lineHeight: 1,
    marginLeft: 2,
    fontSize: 10,
  },
  texttPdf: {
    marginLeft: 5,
    marginRight: 'auto',
    fontSize: 10,
    fontFamily: 'Roboto',
    marginTop: 1,
    marginBottom: 1,
    lineHeight: 1.1,
  },
  texttPdfCategory: {
    marginLeft: 5,
    marginRight: 'auto',
    fontSize: 10,
    fontFamily: 'Roboto',
    marginTop: 1,
    marginBottom: 1,
    lineHeight: 1.1,
    width: '12%',
  },
  texttPdfItem: {
    marginRight: 'auto',
    fontSize: 10,
    fontFamily: 'Roboto',
    marginTop: 1,
    marginBottom: 1,
    lineHeight: 1.1,
  },
  bolder: {
    lineHeight: 1,
    marginLeft: 2,
    fontSize: 12,
  },
  spacer: {
    marginBottom: 6,
    flexDirection: 'row',
  },
  rowend: {
    width: '100%',
    flexDirection: 'row',

    marginBottom: 3,
  },
  currencyrowTotalQuantity: {
    fontSize: 10,
    marginLeft: 92,
    fontWeight: 'bold',
  },
  currencyrowTotalQuantityPdf: {
    fontSize: 10,
    marginLeft: 110,
    fontWeight: 'bold',
  },
  currencyrow2: {
    width: '30%',
  },
  currencyrow2Pdf: {
    width: '25%',
  },
  texth2th: {
    marginLeft: 230,
    fontSize: 10,
  },
  texth2tDeliveryCharges: {
    marginLeft: 96,
    fontSize: 10,
  },
  textTax: {
    marginLeft: 158,
    fontSize: 10,
  },
  texServiceCharges: {
    marginLeft: 99,
    fontSize: 10,
  },
  texth2tDiscount: {
    marginLeft: 133,
    fontSize: 10,
  },
  texth2tCouponCode: {
    marginLeft: 111,
    fontSize: 10,
  },
  texth2t: {
    marginLeft: 151,
    fontSize: 10,
  },
  texttcom: {
    marginLeft: '2px',
    fontSize: 8,
    color: 'black',
    lineHeight: 0.8,
  },
  texth2g: {
    lineHeight: 1.1,
    fontSize: 14,
    fontWeight: 'bold',
    marginTop: 4,
    marginBottom: 6,
    marginLeft: 227,
  },
  texth2g2: {
    lineHeight: 1.1,
    fontSize: 14,
    fontWeight: 'bold',
    marginTop: 4,
    marginBottom: 6,
    marginLeft: 98,
  },
  // currencyrow2PdfGrandTotal: {
  //   width: '25%',
  // },
  texttaddone: {
    lineHeight: 1,
    fontSize: 7,
    color: 'black',
  },
  boldOptionSet: {
    lineHeight: 1,
    fontSize: 10,
  },
  footer: {
    width: '90%',
    flexDirection: 'row',
    marginLeft: 'auto',
    marginRight: 'auto',
    marginTop: 1,
  },
  hst: {
    justifyContent: 'flex-start',
    marginRight: 'auto',
    fontSize: 9,
    color: '#121111',
  },
  phone: {
    justifyContent: 'flex-start',
    marginLeft: 'auto',
    fontSize: 9,
    color: '#121111',
  },
  email: {
    justifyContent: 'flex-start',
    marginLeft: 'auto',
    marginRight: 'auto',
    fontSize: 9,
    color: '#121111',
  },
})
